### PR TITLE
server-api: Add /api/subscriptions/:userId

### LINKED ISSUE #510: api: add subscriptions
see failing contract test resp. GET /api/subscriptions/1 at https://pact.serlo.org/pacts/provider/serlo.org/consumer/api.serlo.org/latest

### PR DESCRIPTION
**Pull request by kulla**
Fixes #510

### CODE REVIEW

File: packages/public/server/src/module/Api/src/Controller/ApiController.php [hunk 1]
```diff
@@ -126,6 +129,37 @@ public function licenseAction()
         }
     }
 
+    public function subscriptionsAction()
+    {
+        try {
+            $userId = (int) $this->params('userId');
+            $user = $this->getUserManager()->getUser(
+                (int) $this->params('userId')
```
Comment (inyono) [inline packages/public/server/src/module/Api/src/Controller/ApiController.php:137]:
```suggestion
                $userId
```

**Review by inyono — APPROVED** [review]

**Comment by inyono** [comment]
Merging before actions are done because GitHub actions are having issues right now.
