### PR TITLE
Test for login with wrong or missing username/password

### LINKED ISSUE #300: Add e2e tests for login process
- [ ] Logging in with wrong password fails
- [ ] Logging in with wrong user name fails
- [ ] Logout process, e.g:
    - given I am logged in as `user`
    - given I am on page `page`
    - when I click on button `Log Out`
    - then I am on page `page`
    - then I am logged out (e.g. button `Log In` occurs and we cannot open `/users/me`)

### PR DESCRIPTION
**Pull request by resirudo**
fixes #300

### CODE REVIEW

File: packages/public/server/__tests-e2e__/login.ts [hunk 1]
```diff
@@ -19,49 +19,129 @@
...
+    await getByPlaceholderText(loginPage, inputUser).then((e) =>
+      e.type('login')
+    )
+    await getByPlaceholderText(loginPage, inputPassword).then((e) =>
+      e.type('123')
+    )
+    const afterLoginPage = await getByText(loginPage, buttonLogin).then(
+      clickForNewPage
+    )
+    //Check if stayed on the page
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:86]:
```suggestion
```
See https://github.com/labs42io/clean-code-typescript#prefer-self-explanatory-code-instead-of-comments

Comment (kulla) [reply packages/public/server/__tests-e2e__/login.ts:86]: You can make two test cases as in https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/__tests__/frontend-proxy.ts#L175-L185 to describe your test code better. (Use an `beforeAll()` instead of `beforeEach()` because performance matters in e2e testing).

File: packages/public/server/__tests-e2e__/login.ts [hunk 2]
```diff
@@ -19,49 +19,129 @@
...
+    ).toBeDefined
+  })
 
-      const afterLoginPage = await getByText(loginPage, buttonLogin).then(
-        clickForNewPage
+  test('correct password and wrong user', async () => {
+    await getByPlaceholderText(loginPage, inputUser).then((e) => e.type('abc'))
+    await getByPlaceholderText(loginPage, inputPassword).then((e) =>
+      e.type('123456')
+    )
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:101]: How about abstracting this code into a function like:

```
test("...", () => {
   typeIntoLoginForm({ password: ..., page: loginPage, user: ... })
}

function typeIntoLoginForm({password, page, user }: { password: string, page:ElementHandle, user: string}) {

}
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 3]
```diff
@@ -19,49 +19,129 @@
...
+  })
 
-      const userPage = await elements
-        .getProfileButton(afterLoginPage)
-        .then(clickForNewPage)
+  test('missing password and correct user', async () => {
+    await getByPlaceholderText(loginPage, inputUser).then((e) =>
+      e.type('login')
+    )
+    await getByPlaceholderText(loginPage, inputPassword).then((e) => e.type(''))
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:130]: Click auf loginButton fehlt

File: packages/public/server/__tests-e2e__/login.ts [hunk 4]
```diff
@@ -19,49 +19,129 @@
...
+    expect(page.url()).toBe(testingServerUrl + pages.login.path)
+  })
+
+  test('correct password and missing user', async () => {
+    await getByPlaceholderText(loginPage, inputUser).then((e) => e.type(''))
+    await getByPlaceholderText(loginPage, inputPassword).then((e) =>
+      e.type('123456')
+    )
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:138]: Klick auf Login-Button fehlt

File: packages/public/server/__tests-e2e__/login.ts [hunk 5]
```diff
@@ -19,49 +19,129 @@
...
   getBySelector,
   getByText,
+  getByRole,
   goto,
 } from './_utils'
+import { ElementHandle } from 'puppeteer'
 
-const examplePages = ['/', '/math', '/math/geometry/triangles']
+describe('login process with correct data', () => {
+  test('correct password and correct user', async () => {
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:34]:
```suggestion
test('login process with correct data', async () => {
```

There is only one test in the describe-block -> thus it can be removed...

File: packages/public/server/__tests-e2e__/login.ts [hunk 6]
```diff
@@ -19,49 +19,129 @@
...
+    await page.setViewport(viewports.desktop)
+    const firstPage = await goto('/math')
+    // ?
+    expect(firstPage).toHaveUrlPath('/math')
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:38]:
```suggestion
```

My bad: this expect does not make sense in this test case

File: packages/public/server/__tests-e2e__/login.ts [hunk 7]
```diff
@@ -19,49 +19,129 @@
...
-      expect(firstPage).toHaveUrlPath(startPath)
+    await getByPlaceholderText(loginPage, inputUser).then((e) =>
+      e.type('login')
+    )
+    await getByPlaceholderText(loginPage, inputPassword).then((e) =>
+      e.type('123456')
+    )
+    const afterLoginPage = await getByText(loginPage, buttonLogin).then(
+      clickForNewPage
+    )
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:54]: you can have a function `clickLoginButton(loginPage)` here.

**Review by kulla — CHANGES_REQUESTED** [review]

File: packages/public/server/__tests-e2e__/entities/staticPage.ts [hunk 8]
```diff
@@ -0,0 +1,78 @@
+/**
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/entities/staticPage.ts:1]: For the Future: Different tasks should be solved in different PRs -> so I can already merge your first PR while you still work on the second.

File: packages/public/server/__tests-e2e__/entities/article.ts [hunk 9]
```diff
@@ -103,4 +103,19 @@ describe('create article', () => {
...
+    const content = 'Hello World! 42'
+
+    const articlePage = await goto(path)
+    await expect(articlePage).toHaveTitle(title)
+
+    const article = await getByItemType(articlePage, articleItemType)
+    await expect(article).toMatchElement('h1', { text: title })
+
+    await expect(article).toMatchElement('*', { text: content })
+  })
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/entities/article.ts:120]:
```suggestion
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 10]
```diff
@@ -19,49 +19,122 @@
...
+    .then(clickForNewPage)
 
-      expect(firstPage).toHaveUrlPath(startPath)
+  expect(loginPage).toHaveUrlPath(pages.login.path)
 
-      const loginPage = await elements
-        .getLoginButton(firstPage)
-        .then(clickForNewPage)
+  const { buttonLogin, inputUser, inputPassword } = pages.login.identifier
+  await typeIntoLoginForm('123456', loginPage, 'login')
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:44]: A structure `typeIntoLoginForm({ user: "...", password: "...", page: loginPage})` would be better to understand (you immediately understand the definition of the arguments / i.e is `'123456'` the password or the user)?. Definition:

```typescript
function typeIntoLoginForm({ page, user, password }: {page: ElementHandle, user: string, password: string }) {
...
}
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 11]
```diff
@@ -19,49 +19,122 @@
...
 
-      expect(loginPage).toHaveUrlPath(pages.login.path)
+  const afterLoginPage = await getByText(loginPage, buttonLogin).then(
+    clickForNewPage
+  )
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:48]: This line can be abstracted away: `clickLoginButton(loginPage)`

File: packages/public/server/__tests-e2e__/login.ts [hunk 12]
```diff
@@ -19,49 +19,122 @@
...
+  page: ElementHandle,
+  user: string
+) {
+  const { inputUser, inputPassword } = pages.login.identifier
+  await getByPlaceholderText(page, inputUser).then((e) => e.type(user))
+  await getByPlaceholderText(page, inputPassword).then((e) => e.type(password))
+}
+async function clickOnLoginButton(page: ElementHandle) {
+  const { buttonLogin } = pages.login.identifier
+  await getByText(page, buttonLogin).then(clickForNewPage)
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:139]:
```suggestion
  await getByText(page,  pages.login.identifier.buttonLogin).then(clickForNewPage)
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 13]
```diff
@@ -19,49 +19,122 @@
...
+        'Mit dieser Kombination ist bei uns kein Benutzer registriert.'
       )
+    ).toBeDefined
+  })
+
+  test('correct password and wrong user', async () => {
+    await typeIntoLoginForm('123456', loginPage, 'abc')
+    const afterLoginPage = await getByText(loginPage, buttonLogin).then(
+      clickForNewPage
+    )
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:90]:
```suggestion
    await clickOnLoginButton(loginPage)
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 14]
```diff
@@ -19,49 +19,122 @@
...
-      const userPage = await elements
-        .getProfileButton(afterLoginPage)
-        .then(clickForNewPage)
+  beforeAll(async () => {
+    await page.setViewport(viewports.desktop)
+    loginPage = await goto('/auth/login')
+  })
+  test('missing password and missing user', async () => {
+    typeIntoLoginForm('', loginPage, '')
+    clickOnLoginButton(loginPage)
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:111]:
```suggestion
    await typeIntoLoginForm('', loginPage, '')
    await clickOnLoginButton(loginPage)
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 15]
```diff
@@ -19,49 +19,122 @@
...
+    expect(page.url()).toBe(testingServerUrl + pages.login.path)
+  })
+
+  test('missing password and correct user', async () => {
+    typeIntoLoginForm('', loginPage, 'login')
+    clickOnLoginButton(loginPage)
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:117]:
```suggestion
    await typeIntoLoginForm('', loginPage, 'login')
    await clickOnLoginButton(loginPage)
```

File: packages/public/server/__tests-e2e__/login.ts (hunk 14 above)
Comment (kulla) [reply packages/public/server/__tests-e2e__/login.ts:111]: Result of both functions is a promise (those are async commands) -> you need to have an await to wait for the action to be done or otherwise the tests will stop them before completion.

File: packages/public/server/__tests-e2e__/login.ts [hunk 16]
```diff
@@ -19,49 +19,122 @@
...
+    expect(page.url()).toBe(testingServerUrl + pages.login.path)
+  })
 
-      expect(userPage).toHaveUrlPath('/user/me')
-      await expect(userPage).toMatchElement('h1', { text: user })
-    })
+  test('correct password and missing user', async () => {
+    typeIntoLoginForm('123456', loginPage, '')
+    clickOnLoginButton(loginPage)
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:123]:
```suggestion
    await typeIntoLoginForm('123456', loginPage, '')
    await clickOnLoginButton(loginPage)
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 17]
```diff
@@ -19,49 +19,122 @@
...
   getByText,
+  getByRole,
   goto,
 } from './_utils'
+import { ElementHandle } from 'puppeteer'
 
-const examplePages = ['/', '/math', '/math/geometry/triangles']
+test('correct password and correct user', async () => {
+  await page.setViewport(viewports.desktop)
+  const firstPage = await goto('/math')
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:35]:
```suggestion
beforeAll(async () => {
  await page.setViewport(viewports.desktop)
})

test('correct password and correct user', async () => {
  const firstPage = await goto('/math')
```

Comment (kulla) [reply packages/public/server/__tests-e2e__/login.ts:35]: So you can delete the `page.setViewport(viewports.desktop)` in the other test cases...

**Review by kulla — CHANGES_REQUESTED** [review]

File: packages/public/server/__tests-e2e__/login.ts (hunk 11 above)
Comment (resirudo) [reply packages/public/server/__tests-e2e__/login.ts:48]: das funktioniert leider nicht, denn hier wird am ende die seite zurückgegeben. Das macht meine Funktion gar nicht, da bei den fehlenden Passowort/User Daten keine neue Seite geöffnet wird

File: packages/public/server/__tests-e2e__/login.ts (hunk 16 above)
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:123]: Alternative

```
    await getLoginButton(loginPage).then(click)
```

or 

```
    await getLoginButton(loginPage).then(clickForNewPage)
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 18]
```diff
@@ -103,38 +100,68 @@ describe('missing login-data', () => {
...
-) {
-  const { inputUser, inputPassword } = pages.login.identifier
-  await getByPlaceholderText(page, inputUser).then((e) => e.type(user))
-  await getByPlaceholderText(page, inputPassword).then((e) => e.type(password))
+  password: string
+}) {
+  {
+    await typeIntoLoginForm(arg)
+    const logbutton = elements.getLoginButton(arg.page)
+    ;(await logbutton).click
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:142]:
```suggestion
    await elements.getLoginButton(arg.page).then(click)
```

File: packages/public/server/__tests-e2e__/login.ts [hunk 19]
```diff
@@ -103,38 +100,68 @@ describe('missing login-data', () => {
...
+
+async function typeIntoLoginFormAndWaitForNewPage(arg: {
+  page: ElementHandle
+  user: string
+  password: string
+}) {
+  {
+    await typeIntoLoginForm(arg)
+    const { buttonLogin } = pages.login.identifier
+    return await getByText(arg.page, 'Login').then(clickForNewPage)
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:154]:
```suggestion
    return getByText(arg.page, 'Login').then(clickForNewPage)
```

It should also work without `await`. I have no clear opinion what is better (I just want to point out, that this is an alternative). You can decide what you want to use :smile:

**Review by kulla — CHANGES_REQUESTED** [review]

File: packages/public/server/__tests-e2e__/login.ts (hunk 18 above)
Comment (resirudo) [reply packages/public/server/__tests-e2e__/login.ts:142]: Das funktioniert so leider auch nicht, dann kommt nämlich wieder der Fehler Execution context was destroyed, most likely because of a navigation.

File: packages/public/server/__tests-e2e__/login.ts [hunk 20]
```diff
@@ -19,49 +19,144 @@
...
     })
   })
 })
+
+async function typeIntoLoginForm(arg: {
+  page: ElementHandle
+  user: string
+  password: string
+}) {
+  const { inputUser, inputPassword } = pages.login.identifier
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:132]: Can you check whether we can delete `pages.login` of `_config.ts` and hard code its elements into this file?

File: packages/public/server/__tests-e2e__/login.ts [hunk 21]
```diff
@@ -19,49 +19,144 @@
...
-const examplePages = ['/', '/math', '/math/geometry/triangles']
+beforeAll(async () => {
+  await page.setViewport(viewports.desktop)
+})
+
+test('correct password and correct user', async () => {
+  const firstPage = await goto('/math')
+
+  const loginPage = await elements
+    .getLoginButtonInHeaderMenu(firstPage)
```
Comment (kulla) [inline packages/public/server/__tests-e2e__/login.ts:41]: Can you move this function into this file?

**Review by kulla — CHANGES_REQUESTED** [review]
Two small improvements and then it is ready to be merged. Note that I have refactored this file a little bit. I can explain my changes tomorrow when we meet.

**Review by kulla — APPROVED** [review]
