### PR TITLE
Handle entities without subjects at /entity/unrevised

### LINKED ISSUE #167: Move flatmap function to a global utility file
The function https://github.com/serlo/serlo.org/blob/master/packages/public/server/src/module/Entity/src/Entity/Entity/Entity.php#L265-L267 should be moved to a global utility file so that it can be used everywhere. Then also Unit tests would be great for this function.

### LINKED ISSUE #237: https://en.serlo.org/entity/unrevised broken
Sentry Issue: [SERLO-ORG-SERVER-25](https://sentry.io/organizations/serlo/issues/1457495209/?referrer=github_integration)

```
ErrorException: array_merge() expects at least 1 parameter, 0 given
  File "module/Entity/src/Entity/Entity/Entity.php", line 266, in handleError
    return array_merge(...array_map($map, $array));
  File "vendor/sentry/sentry/lib/Raven/ErrorHandler.php", line 0, in array_merge
    Raven_ErrorHandler->handleError
  File "module/Entity/src/Entity/Entity/Entity.php", line 266, in Entity\Entity\{closure}
    return array_merge(...array_map($map, $array));
  File "module/Entity/src/Entity/Entity/Entity.php", line 275, in getSubjects
    }, $this->getParents('link')->toArray());
  File "data/DoctrineORMModule/Proxy/__CG__EntityEntityEntity.php", line 393, in getSubjects
    return parent::getSubjects();
...
(13 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by kulla**
Fixes #237 (and also fixes #167 ) by showing revisions of entities without a subject at `/entity/unrevised`:

2020-01-22-010707_932x512_scrot

This PR is based on #240 which should be merged first.

### CODE REVIEW

File: packages/public/server/src/module/Common/src/Common/Utils.php [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+ * @license   http://www.apache.org/licenses/LICENSE-2.0 Apache License 2.0
+ * @link      https://github.com/serlo-org/serlo.org for the canonical source repository
+ */
+namespace Common;
+
+abstract class Utils
+{
+    public static function array_flatmap($map, $array)
+    {
+        return !empty($array) ? array_merge(...array_map($map, $array)) : [];
```
Comment (inyono) [inline packages/public/server/src/module/Common/src/Common/Utils.php]: IMHO should be flipped (if-else with negation is often a trip up)

File: packages/public/server/src/module/Common/test/CommonTest/UtilsTest.php [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+
+class UtilsTest extends TestCase
+{
+    public function testArrayFlatmap()
+    {
+        $double = function ($x) {
+            return [$x, $x];
+        };
+
+        $this->assertEquals(Utils::array_flatmap($double, []), []);
```
Comment (inyono) [inline packages/public/server/src/module/Common/test/CommonTest/UtilsTest.php]: Should be multiple tests. One test case should usually test only one thing. Otherwise, debugging a failing test is kinda annoying

File: packages/public/server/src/module/Entity/src/Entity/Entity/Entity.php [hunk 3]
```diff
@@ -262,17 +263,15 @@ public function getTaxonomyTerms()
...
-        };
-
-        $subjects = !$this->getTaxonomyTerms()->isEmpty()
-                    ? $this->getTaxonomyTerms()->map(function ($term) {
-                        return $term->getSecondLevelAncestor();
-                    })->toArray()
-                    : $flatmap(function ($parent) {
-                        return $parent->getSubjects();
-                    }, $this->getParents('link')->toArray());
+        if (!$this->getTaxonomyTerms()->isEmpty()) {
```
Comment (inyono) [inline packages/public/server/src/module/Entity/src/Entity/Entity/Entity.php]: Same as above, should be flipped
